import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { AppShell } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { listPastoralAssignees, listPastoralQueue, savePastoralFollowup, type PastoralQueueItem } from "@/lib/pastoral-followups.functions";
import { HandHeart, Loader2, MessageCircle, CalendarClock, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/acompanhamento")({ component: PastoralFollowupPage });
const labels = { visitor: "Visitante", decision: "Decisão", prayer: "Oração", absence: "Ausência" };

function PastoralFollowupPage() {
  const qc = useQueryClient(); const list = useServerFn(listPastoralQueue); const listAssignees = useServerFn(listPastoralAssignees); const save = useServerFn(savePastoralFollowup);
  const { data = [], isLoading } = useQuery({ queryKey: ["pastoral-queue"], queryFn: () => list() });
  const [sourceFilter, setSourceFilter] = useState<"all" | PastoralQueueItem["source_type"]>("all");
  const [statusFilter, setStatusFilter] = useState<"all" | "open" | "in_progress">("all");
  const filtered = data.filter((item) => (sourceFilter === "all" || item.source_type === sourceFilter) && (statusFilter === "all" || (item.followup?.status ?? "open") === statusFilter));
  const { data: assignees = [] } = useQuery({ queryKey: ["pastoral-assignees"], queryFn: () => listAssignees() });
  const mutation = useMutation({ mutationFn: save, onSuccess: () => { qc.invalidateQueries({ queryKey: ["pastoral-queue"] }); toast.success("Acompanhamento atualizado"); }, onError: (e) => toast.error(e instanceof Error ? e.message : "Não foi possível salvar") });
  return <AppShell><div className="w-full space-y-6"><header className="rounded-xl border bg-gradient-to-br from-primary/[.10] via-background to-background p-6"><div className="flex items-center gap-3"><span className="rounded-lg bg-primary p-2.5 text-primary-foreground"><HandHeart className="h-6 w-6" /></span><div><h1 className="text-2xl font-semibold">Acompanhamento pastoral</h1><p className="mt-1 text-sm text-muted-foreground">Uma fila de cuidado para não perder nenhum pedido, decisão ou primeira visita.</p></div></div><div className="mt-5 flex gap-5 text-sm"><span><b className="text-lg">{data.length}</b> em acompanhamento</span><span><b className="text-lg">{data.filter(x => x.followup?.next_contact_at).length}</b> com próximo contato</span></div></header>
  <div className="flex flex-wrap gap-2"><select className="h-9 rounded-md border bg-background px-2 text-sm" value={sourceFilter} onChange={e=>setSourceFilter(e.target.value as typeof sourceFilter)}><option value="all">Todas as origens</option><option value="visitor">Visitantes</option><option value="decision">Decisões</option><option value="prayer">Orações</option><option value="absence">Ausências</option></select><select className="h-9 rounded-md border bg-background px-2 text-sm" value={statusFilter} onChange={e=>setStatusFilter(e.target.value as typeof statusFilter)}><option value="all">Todos os status</option><option value="open">Abertos</option><option value="in_progress">Em andamento</option></select></div>{isLoading ? <p className="text-sm text-muted-foreground">Carregando a fila...</p> : filtered.length === 0 ? <Card className="p-10 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-600"/><p className="mt-3 font-medium">Nenhum acompanhamento neste filtro.</p><p className="mt-1 text-sm text-muted-foreground">Ajuste os filtros ou aguarde novas entradas.</p></Card> : <div className="grid gap-3 xl:grid-cols-2">{filtered.map(item => <QueueCard key={`${item.source_type}-${item.source_id}`} item={item} assignees={assignees} saving={mutation.isPending} onSave={(payload) => mutation.mutate({ data: payload })}/>)}</div>}</div></AppShell>;
}
function QueueCard({ item, assignees, saving, onSave }: { item: PastoralQueueItem; assignees:Array<{user_id:string;role:string}>; saving:boolean; onSave: (data: {source_type:PastoralQueueItem["source_type"];source_id:string;status:"open"|"in_progress"|"done";assignee_user_id:string|null;next_contact_at:string|null;outcome:string|null;notes:string|null})=>void }) {
 const [date,setDate]=useState(item.followup?.next_contact_at ?? ""); const [notes,setNotes]=useState(item.followup?.notes ?? ""); const [status,setStatus]=useState<"open"|"in_progress"|"done">(item.followup?.status ?? "open"); const [assignee,setAssignee]=useState(item.followup?.assignee_user_id ?? "");
 const wa=item.phone ? `https://wa.me/55${item.phone.replace(/\D/g, "")}` : null;
 return <Card className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><p className="font-semibold">{item.name}</p><Badge variant="outline">{labels[item.source_type]}</Badge></div><p className="mt-1 text-xs text-muted-foreground">Recebido em {new Date(item.created_at).toLocaleDateString("pt-BR")}</p></div>{wa&&<a href={wa} target="_blank" rel="noreferrer"><Button size="sm" variant="outline"><MessageCircle className="mr-1 h-3.5 w-3.5"/> WhatsApp</Button></a>}</div>{item.detail&&<p className="mt-3 rounded-md bg-muted/50 p-2.5 text-sm whitespace-pre-wrap">{item.detail}</p>}<div className="mt-3 grid gap-2 sm:grid-cols-2"><Input type="date" value={date} onChange={e=>setDate(e.target.value)} aria-label="Próximo contato"/><select className="h-9 rounded-md border bg-background px-2 text-sm" value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="open">Aberto</option><option value="in_progress">Em andamento</option><option value="done">Concluído</option></select><select className="h-9 rounded-md border bg-background px-2 text-sm sm:col-span-2" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Sem responsável</option>{assignees.map(a=><option key={a.user_id} value={a.user_id}>{a.role}</option>)}</select></div><Textarea className="mt-2" rows={2} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Registro do cuidado e próximos passos"/><Button className="mt-2" size="sm" disabled={saving} onClick={()=>onSave({source_type:item.source_type,source_id:item.source_id,status,assignee_user_id:assignee||null,next_contact_at:date||null,outcome:null,notes:notes||null})}>{saving?<Loader2 className="mr-1 h-3.5 w-3.5 animate-spin"/>:<CalendarClock className="mr-1 h-3.5 w-3.5"/>}Salvar</Button>{item.history.length>0&&<div className="mt-3 border-t pt-3"><p className="text-xs font-medium text-muted-foreground">Últimas ações</p>{item.history.map((event,index)=><p key={`${event.created_at}-${index}`} className="mt-1 text-xs text-muted-foreground">{new Date(event.created_at).toLocaleDateString("pt-BR")} · {event.status}{event.note?`: ${event.note}`:""}</p>)}</div>}</Card>;
}
