import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BarChart3, ChefHat, CircleDollarSign, QrCode, ShieldCheck, Store, UtensilsCrossed } from "lucide-react";

export const Route = createFileRoute("/festejo")({ component: FestejoLanding });

function FestejoLanding() {
  return <main className="min-h-screen overflow-hidden bg-[#fffaf0] text-[#23342d]">
    <section className="relative bg-[#19352d] px-6 pb-24 pt-6 text-[#fff8e7] sm:px-10 lg:px-16">
      <div className="mx-auto max-w-6xl"><nav className="flex items-center justify-between"><Link to="/" className="font-display text-lg font-semibold tracking-tight">Festejo<span className="text-[#f7b955]">.</span></Link><a href="/login" className="text-sm text-white/75 hover:text-white">Já tenho acesso</a></nav><div className="relative py-20 lg:py-28"><div className="absolute -right-16 top-0 hidden h-96 w-96 rounded-full border-[55px] border-[#f7b955]/15 lg:block" /><p className="text-sm font-semibold tracking-[.18em] text-[#f7b955]">EVENTOS QUE FAZEM BEM</p><h1 className="mt-5 max-w-3xl font-display text-5xl font-semibold leading-[.95] tracking-tight sm:text-6xl lg:text-7xl">A festa da sua comunidade, sem fila e sem confusão.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-white/75">Barracas, caixa, pedidos e prestação de contas reunidos em uma experiência feita para eventos beneficentes.</p><div className="mt-9 flex flex-wrap gap-3"><a href="mailto:contato@digitallagos.com.br?subject=Quero%20conhecer%20o%20Festejo" className="inline-flex items-center rounded-full bg-[#f7b955] px-5 py-3 text-sm font-semibold text-[#19352d] transition hover:bg-[#ffd37c]">Quero conhecer <ArrowRight className="ml-2 h-4 w-4" /></a><a href="#como-funciona" className="inline-flex items-center rounded-full border border-white/25 px-5 py-3 text-sm font-semibold text-white transition hover:bg-white/10">Como funciona</a></div></div></div>
    </section>
    <section id="como-funciona" className="mx-auto max-w-6xl px-6 py-20 sm:px-10 lg:px-16"><p className="text-sm font-semibold tracking-[.18em] text-[#c85b3f]">OPERAÇÃO NO BOLSO</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-semibold tracking-tight sm:text-5xl">Cada barraca flui. Cada real aparece.</h2><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[[Store,"Barracas vivas","Cardápio, estoque e equipe por ponto de venda."],[QrCode,"QR para pedir","Pedido antecipado e retirada sem confusão."],[CircleDollarSign,"Caixa confiável","Pix, cartão e dinheiro registrados com responsável."],[BarChart3,"Resultado em tempo real","Acompanhe o que vende, o que falta e o resultado."]].map(([Icon,title,text])=>{const I=Icon as typeof Store;return <article key={title as string} className="rounded-3xl border border-[#eadfcb] bg-white p-6 shadow-[0_12px_30px_rgb(62,45,24,.05)]"><I className="h-6 w-6 text-[#c85b3f]"/><h3 className="mt-9 font-display text-xl font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-relaxed text-[#6d695f]">{text as string}</p></article>})}</div></section>
    <section className="bg-[#e8b64b] px-6 py-16 sm:px-10 lg:px-16"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><div className="flex items-center gap-2 text-[#3f361d]"><UtensilsCrossed className="h-5 w-5"/><span className="text-xs font-semibold tracking-[.16em]">ASSINATURA MENSAL</span></div><h2 className="mt-3 font-display text-3xl font-semibold tracking-tight text-[#2e321d] sm:text-4xl">Sua próxima festa merece uma operação à altura.</h2></div><a href="mailto:contato@digitallagos.com.br?subject=Quero%20saber%20sobre%20a%20assinatura%20Festejo" className="inline-flex shrink-0 items-center rounded-full bg-[#19352d] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#26493d]">Falar sobre assinatura <ArrowRight className="ml-2 h-4 w-4" /></a></div></section>
    <footer className="mx-auto flex max-w-6xl items-center justify-between px-6 py-8 text-sm text-[#777064] sm:px-10 lg:px-16"><span className="flex items-center gap-2"><ChefHat className="h-4 w-4 text-[#c85b3f]"/> Festejo</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4"/> Tecnologia para a comunidade</span></footer>
  </main>;
}
