import { createFileRoute, Link } from "@tanstack/react-router";
import type { ReactNode } from "react";

export const Route = createFileRoute("/termos-de-uso")({ component: TermsPage });

function TermsPage() {
  return <LegalLayout title="Termos de Uso" updated="16 de julho de 2026"><p>Estes Termos regulam o uso da plataforma SuaIgreja, fornecida pela Digital Lagos (“Plataforma”). Ao criar uma conta ou usar a Plataforma, a organização contratante e seus usuários autorizados concordam com estes Termos.</p><h2>1. Papel das partes</h2><p>A organização contratante define as finalidades e os meios principais para tratar dados de seus participantes, equipe e visitantes, atuando em regra como controladora. A Digital Lagos disponibiliza e opera a infraestrutura da Plataforma conforme suas instruções, atuando em regra como operadora. Cada parte deve cumprir as obrigações que lhe cabem na legislação aplicável.</p><h2>2. Conta, acesso e segurança</h2><p>A organização é responsável por indicar usuários autorizados, administrar permissões e manter credenciais confidenciais. É proibido compartilhar contas, tentar acessar dados de outra organização ou usar a Plataforma para finalidade ilícita.</p><h2>3. Dados e conteúdo</h2><p>A organização declara que possui base legal adequada para inserir e tratar os dados na Plataforma, especialmente quando envolver dados pessoais sensíveis, como convicção religiosa. A Plataforma não deve ser usada para discriminação, decisões automatizadas inadequadas ou coleta excessiva de dados.</p><h2>4. Serviços de terceiros</h2><p>Integrações de pagamento, mensagens, hospedagem e autenticação podem envolver provedores terceiros. Seu uso pode exigir termos e políticas próprios. Dados de cartão não devem ser inseridos manualmente na Plataforma.</p><h2>5. Suspensão e encerramento</h2><p>Podemos restringir acesso em caso de violação destes Termos, risco de segurança, obrigação legal ou inadimplência, preservado o que a lei exigir. O encerramento não elimina automaticamente registros que precisem ser mantidos por obrigação legal, defesa de direitos ou auditoria.</p><h2>6. Alterações e contato</h2><p>Atualizações relevantes serão publicadas com nova versão e poderão exigir novo aceite. Para dúvidas sobre estes Termos, escreva para contato@digitallagos.com.br.</p></LegalLayout>;
}

function LegalLayout({ title, updated, children }: { title: string; updated: string; children: ReactNode }) {
  return <main className="min-h-screen bg-stone-50 px-4 py-10 text-stone-800"><article className="mx-auto max-w-3xl rounded-2xl border bg-white p-6 shadow-sm sm:p-10"><Link to="/login" className="text-sm font-medium text-primary underline underline-offset-4">← Voltar para acesso</Link><p className="mt-8 text-xs font-semibold tracking-[.16em] text-stone-500">SUAIGREJA · VERSÃO 2026-07-16</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-sm text-stone-500">Última atualização: {updated}</p><div className="prose prose-stone mt-8 max-w-none prose-headings:font-display prose-headings:font-semibold prose-p:leading-7">{children}</div></article></main>;
}
