/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VSiteIdRouteImport } from './routes/v.$siteId'
import { Route as ReciboDonationIdRouteImport } from './routes/recibo.$donationId'
import { Route as OSiteIdRouteImport } from './routes/o.$siteId'
import { Route as NSlugRouteImport } from './routes/n.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as EnderecosSlugRouteImport } from './routes/enderecos.$slug'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as CheckinSessionIdRouteImport } from './routes/checkin.$sessionId'
import { Route as CMemberIdRouteImport } from './routes/c.$memberId'
import { Route as ASiteIdRouteImport } from './routes/a.$siteId'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated.whatsapp'
import { Route as AuthenticatedVisitantesRouteImport } from './routes/_authenticated.visitantes'
import { Route as AuthenticatedTypesRouteImport } from './routes/_authenticated.types'
import { Route as AuthenticatedTransmissoesRouteImport } from './routes/_authenticated.transmissoes'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedOracoesRouteImport } from './routes/_authenticated.oracoes'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedMembrosRouteImport } from './routes/_authenticated.membros'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated.marketplace'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated.locations'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated.hub'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated.finances'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated.eventos'
import { Route as AuthenticatedEmbedRouteImport } from './routes/_authenticated.embed'
import { Route as AuthenticatedEbdRouteImport } from './routes/_authenticated.ebd'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated.documentos'
import { Route as AuthenticatedDevocionalRouteImport } from './routes/_authenticated.devocional'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated.checkin'
import { Route as AuthenticatedCelulasRouteImport } from './routes/_authenticated.celulas'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated.agenda'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as NSlugPostIdRouteImport } from './routes/n.$slug.$postId'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api.public.mercadopago-webhook'
import { Route as ApiPublicAtivopayWebhookRouteImport } from './routes/api.public.ativopay-webhook'
import { Route as AuthenticatedMarketplaceSlugRouteImport } from './routes/_authenticated.marketplace.$slug'
import { Route as AuthenticatedAdminTestDataRouteImport } from './routes/_authenticated.admin.test-data'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated.admin.products'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated.admin.payments'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated.admin.feedback'
import { Route as ApiPublicInstagramCallbackRouteImport } from './routes/api.public.instagram.callback'
import { Route as ApiPublicCronWhatsappBirthdaysRouteImport } from './routes/api.public.cron.whatsapp-birthdays'
import { Route as ApiPublicCronTitheReminderRouteImport } from './routes/api.public.cron.tithe-reminder'
import { Route as ApiPublicAgendaSiteIdRouteImport } from './routes/api.public.agenda.$siteId'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VSiteIdRoute = VSiteIdRouteImport.update({
  id: '/v/$siteId',
  path: '/v/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReciboDonationIdRoute = ReciboDonationIdRouteImport.update({
  id: '/recibo/$donationId',
  path: '/recibo/$donationId',
  getParentRoute: () => rootRouteImport,
} as any)
const OSiteIdRoute = OSiteIdRouteImport.update({
  id: '/o/$siteId',
  path: '/o/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnderecosSlugRoute = EnderecosSlugRouteImport.update({
  id: '/enderecos/$slug',
  path: '/enderecos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinSessionIdRoute = CheckinSessionIdRouteImport.update({
  id: '/checkin/$sessionId',
  path: '/checkin/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CMemberIdRoute = CMemberIdRouteImport.update({
  id: '/c/$memberId',
  path: '/c/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const ASiteIdRoute = ASiteIdRouteImport.update({
  id: '/a/$siteId',
  path: '/a/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitantesRoute = AuthenticatedVisitantesRouteImport.update({
  id: '/visitantes',
  path: '/visitantes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTypesRoute = AuthenticatedTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransmissoesRoute =
  AuthenticatedTransmissoesRouteImport.update({
    id: '/transmissoes',
    path: '/transmissoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOracoesRoute = AuthenticatedOracoesRouteImport.update({
  id: '/oracoes',
  path: '/oracoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembrosRoute = AuthenticatedMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmbedRoute = AuthenticatedEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEbdRoute = AuthenticatedEbdRouteImport.update({
  id: '/ebd',
  path: '/ebd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevocionalRoute = AuthenticatedDevocionalRouteImport.update({
  id: '/devocional',
  path: '/devocional',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCelulasRoute = AuthenticatedCelulasRouteImport.update({
  id: '/celulas',
  path: '/celulas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const NSlugPostIdRoute = NSlugPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => NSlugRoute,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAtivopayWebhookRoute =
  ApiPublicAtivopayWebhookRouteImport.update({
    id: '/api/public/ativopay-webhook',
    path: '/api/public/ativopay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMarketplaceSlugRoute =
  AuthenticatedMarketplaceSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedAdminTestDataRoute =
  AuthenticatedAdminTestDataRouteImport.update({
    id: '/admin/test-data',
    path: '/admin/test-data',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/admin/feedback',
    path: '/admin/feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicInstagramCallbackRoute =
  ApiPublicInstagramCallbackRouteImport.update({
    id: '/api/public/instagram/callback',
    path: '/api/public/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronWhatsappBirthdaysRoute =
  ApiPublicCronWhatsappBirthdaysRouteImport.update({
    id: '/api/public/cron/whatsapp-birthdays',
    path: '/api/public/cron/whatsapp-birthdays',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTitheReminderRoute =
  ApiPublicCronTitheReminderRouteImport.update({
    id: '/api/public/cron/tithe-reminder',
    path: '/api/public/cron/tithe-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgendaSiteIdRoute = ApiPublicAgendaSiteIdRouteImport.update({
  id: '/api/public/agenda/$siteId',
  path: '/api/public/agenda/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/update-password': typeof UpdatePasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/celulas': typeof AuthenticatedCelulasRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devocional': typeof AuthenticatedDevocionalRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/ebd': typeof AuthenticatedEbdRoute
  '/embed': typeof AuthenticatedEmbedRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/hub': typeof AuthenticatedHubRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/membros': typeof AuthenticatedMembrosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/oracoes': typeof AuthenticatedOracoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transmissoes': typeof AuthenticatedTransmissoesRoute
  '/types': typeof AuthenticatedTypesRoute
  '/visitantes': typeof AuthenticatedVisitantesRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/a/$siteId': typeof ASiteIdRoute
  '/c/$memberId': typeof CMemberIdRoute
  '/checkin/$sessionId': typeof CheckinSessionIdRoute
  '/d/$slug': typeof DSlugRoute
  '/e/$slug': typeof ESlugRoute
  '/enderecos/$slug': typeof EnderecosSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/n/$slug': typeof NSlugRouteWithChildren
  '/o/$siteId': typeof OSiteIdRoute
  '/recibo/$donationId': typeof ReciboDonationIdRoute
  '/v/$siteId': typeof VSiteIdRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/test-data': typeof AuthenticatedAdminTestDataRoute
  '/marketplace/$slug': typeof AuthenticatedMarketplaceSlugRoute
  '/api/public/ativopay-webhook': typeof ApiPublicAtivopayWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/n/$slug/$postId': typeof NSlugPostIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/agenda/$siteId': typeof ApiPublicAgendaSiteIdRoute
  '/api/public/cron/tithe-reminder': typeof ApiPublicCronTitheReminderRoute
  '/api/public/cron/whatsapp-birthdays': typeof ApiPublicCronWhatsappBirthdaysRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/update-password': typeof UpdatePasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/celulas': typeof AuthenticatedCelulasRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devocional': typeof AuthenticatedDevocionalRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/ebd': typeof AuthenticatedEbdRoute
  '/embed': typeof AuthenticatedEmbedRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/hub': typeof AuthenticatedHubRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/membros': typeof AuthenticatedMembrosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/oracoes': typeof AuthenticatedOracoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transmissoes': typeof AuthenticatedTransmissoesRoute
  '/types': typeof AuthenticatedTypesRoute
  '/visitantes': typeof AuthenticatedVisitantesRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/a/$siteId': typeof ASiteIdRoute
  '/c/$memberId': typeof CMemberIdRoute
  '/checkin/$sessionId': typeof CheckinSessionIdRoute
  '/d/$slug': typeof DSlugRoute
  '/e/$slug': typeof ESlugRoute
  '/enderecos/$slug': typeof EnderecosSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/n/$slug': typeof NSlugRouteWithChildren
  '/o/$siteId': typeof OSiteIdRoute
  '/recibo/$donationId': typeof ReciboDonationIdRoute
  '/v/$siteId': typeof VSiteIdRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/test-data': typeof AuthenticatedAdminTestDataRoute
  '/marketplace/$slug': typeof AuthenticatedMarketplaceSlugRoute
  '/api/public/ativopay-webhook': typeof ApiPublicAtivopayWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/n/$slug/$postId': typeof NSlugPostIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/agenda/$siteId': typeof ApiPublicAgendaSiteIdRoute
  '/api/public/cron/tithe-reminder': typeof ApiPublicCronTitheReminderRoute
  '/api/public/cron/whatsapp-birthdays': typeof ApiPublicCronWhatsappBirthdaysRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/celulas': typeof AuthenticatedCelulasRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devocional': typeof AuthenticatedDevocionalRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/ebd': typeof AuthenticatedEbdRoute
  '/_authenticated/embed': typeof AuthenticatedEmbedRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/_authenticated/membros': typeof AuthenticatedMembrosRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/oracoes': typeof AuthenticatedOracoesRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transmissoes': typeof AuthenticatedTransmissoesRoute
  '/_authenticated/types': typeof AuthenticatedTypesRoute
  '/_authenticated/visitantes': typeof AuthenticatedVisitantesRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/a/$siteId': typeof ASiteIdRoute
  '/c/$memberId': typeof CMemberIdRoute
  '/checkin/$sessionId': typeof CheckinSessionIdRoute
  '/d/$slug': typeof DSlugRoute
  '/e/$slug': typeof ESlugRoute
  '/enderecos/$slug': typeof EnderecosSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/n/$slug': typeof NSlugRouteWithChildren
  '/o/$siteId': typeof OSiteIdRoute
  '/recibo/$donationId': typeof ReciboDonationIdRoute
  '/v/$siteId': typeof VSiteIdRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/test-data': typeof AuthenticatedAdminTestDataRoute
  '/_authenticated/marketplace/$slug': typeof AuthenticatedMarketplaceSlugRoute
  '/api/public/ativopay-webhook': typeof ApiPublicAtivopayWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/n/$slug/$postId': typeof NSlugPostIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/agenda/$siteId': typeof ApiPublicAgendaSiteIdRoute
  '/api/public/cron/tithe-reminder': typeof ApiPublicCronTitheReminderRoute
  '/api/public/cron/whatsapp-birthdays': typeof ApiPublicCronWhatsappBirthdaysRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/login'
    | '/update-password'
    | '/agenda'
    | '/billing'
    | '/celulas'
    | '/checkin'
    | '/dashboard'
    | '/devocional'
    | '/documentos'
    | '/ebd'
    | '/embed'
    | '/eventos'
    | '/finances'
    | '/hub'
    | '/locations'
    | '/marketplace'
    | '/membros'
    | '/onboarding'
    | '/oracoes'
    | '/relatorios'
    | '/settings'
    | '/transmissoes'
    | '/types'
    | '/visitantes'
    | '/whatsapp'
    | '/a/$siteId'
    | '/c/$memberId'
    | '/checkin/$sessionId'
    | '/d/$slug'
    | '/e/$slug'
    | '/enderecos/$slug'
    | '/eventos/$slug'
    | '/n/$slug'
    | '/o/$siteId'
    | '/recibo/$donationId'
    | '/v/$siteId'
    | '/admin/feedback'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/test-data'
    | '/marketplace/$slug'
    | '/api/public/ativopay-webhook'
    | '/api/public/mercadopago-webhook'
    | '/n/$slug/$postId'
    | '/admin/'
    | '/api/public/agenda/$siteId'
    | '/api/public/cron/tithe-reminder'
    | '/api/public/cron/whatsapp-birthdays'
    | '/api/public/instagram/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/update-password'
    | '/agenda'
    | '/billing'
    | '/celulas'
    | '/checkin'
    | '/dashboard'
    | '/devocional'
    | '/documentos'
    | '/ebd'
    | '/embed'
    | '/eventos'
    | '/finances'
    | '/hub'
    | '/locations'
    | '/marketplace'
    | '/membros'
    | '/onboarding'
    | '/oracoes'
    | '/relatorios'
    | '/settings'
    | '/transmissoes'
    | '/types'
    | '/visitantes'
    | '/whatsapp'
    | '/a/$siteId'
    | '/c/$memberId'
    | '/checkin/$sessionId'
    | '/d/$slug'
    | '/e/$slug'
    | '/enderecos/$slug'
    | '/eventos/$slug'
    | '/n/$slug'
    | '/o/$siteId'
    | '/recibo/$donationId'
    | '/v/$siteId'
    | '/admin/feedback'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/test-data'
    | '/marketplace/$slug'
    | '/api/public/ativopay-webhook'
    | '/api/public/mercadopago-webhook'
    | '/n/$slug/$postId'
    | '/admin'
    | '/api/public/agenda/$siteId'
    | '/api/public/cron/tithe-reminder'
    | '/api/public/cron/whatsapp-birthdays'
    | '/api/public/instagram/callback'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/login'
    | '/update-password'
    | '/_authenticated/agenda'
    | '/_authenticated/billing'
    | '/_authenticated/celulas'
    | '/_authenticated/checkin'
    | '/_authenticated/dashboard'
    | '/_authenticated/devocional'
    | '/_authenticated/documentos'
    | '/_authenticated/ebd'
    | '/_authenticated/embed'
    | '/_authenticated/eventos'
    | '/_authenticated/finances'
    | '/_authenticated/hub'
    | '/_authenticated/locations'
    | '/_authenticated/marketplace'
    | '/_authenticated/membros'
    | '/_authenticated/onboarding'
    | '/_authenticated/oracoes'
    | '/_authenticated/relatorios'
    | '/_authenticated/settings'
    | '/_authenticated/transmissoes'
    | '/_authenticated/types'
    | '/_authenticated/visitantes'
    | '/_authenticated/whatsapp'
    | '/a/$siteId'
    | '/c/$memberId'
    | '/checkin/$sessionId'
    | '/d/$slug'
    | '/e/$slug'
    | '/enderecos/$slug'
    | '/eventos/$slug'
    | '/n/$slug'
    | '/o/$siteId'
    | '/recibo/$donationId'
    | '/v/$siteId'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/test-data'
    | '/_authenticated/marketplace/$slug'
    | '/api/public/ativopay-webhook'
    | '/api/public/mercadopago-webhook'
    | '/n/$slug/$postId'
    | '/_authenticated/admin/'
    | '/api/public/agenda/$siteId'
    | '/api/public/cron/tithe-reminder'
    | '/api/public/cron/whatsapp-birthdays'
    | '/api/public/instagram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  ASiteIdRoute: typeof ASiteIdRoute
  CMemberIdRoute: typeof CMemberIdRoute
  CheckinSessionIdRoute: typeof CheckinSessionIdRoute
  DSlugRoute: typeof DSlugRoute
  ESlugRoute: typeof ESlugRoute
  EnderecosSlugRoute: typeof EnderecosSlugRoute
  EventosSlugRoute: typeof EventosSlugRoute
  NSlugRoute: typeof NSlugRouteWithChildren
  OSiteIdRoute: typeof OSiteIdRoute
  ReciboDonationIdRoute: typeof ReciboDonationIdRoute
  VSiteIdRoute: typeof VSiteIdRoute
  ApiPublicAtivopayWebhookRoute: typeof ApiPublicAtivopayWebhookRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicAgendaSiteIdRoute: typeof ApiPublicAgendaSiteIdRoute
  ApiPublicCronTitheReminderRoute: typeof ApiPublicCronTitheReminderRoute
  ApiPublicCronWhatsappBirthdaysRoute: typeof ApiPublicCronWhatsappBirthdaysRoute
  ApiPublicInstagramCallbackRoute: typeof ApiPublicInstagramCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$siteId': {
      id: '/v/$siteId'
      path: '/v/$siteId'
      fullPath: '/v/$siteId'
      preLoaderRoute: typeof VSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibo/$donationId': {
      id: '/recibo/$donationId'
      path: '/recibo/$donationId'
      fullPath: '/recibo/$donationId'
      preLoaderRoute: typeof ReciboDonationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$siteId': {
      id: '/o/$siteId'
      path: '/o/$siteId'
      fullPath: '/o/$siteId'
      preLoaderRoute: typeof OSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enderecos/$slug': {
      id: '/enderecos/$slug'
      path: '/enderecos/$slug'
      fullPath: '/enderecos/$slug'
      preLoaderRoute: typeof EnderecosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$sessionId': {
      id: '/checkin/$sessionId'
      path: '/checkin/$sessionId'
      fullPath: '/checkin/$sessionId'
      preLoaderRoute: typeof CheckinSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$memberId': {
      id: '/c/$memberId'
      path: '/c/$memberId'
      fullPath: '/c/$memberId'
      preLoaderRoute: typeof CMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$siteId': {
      id: '/a/$siteId'
      path: '/a/$siteId'
      fullPath: '/a/$siteId'
      preLoaderRoute: typeof ASiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visitantes': {
      id: '/_authenticated/visitantes'
      path: '/visitantes'
      fullPath: '/visitantes'
      preLoaderRoute: typeof AuthenticatedVisitantesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/types': {
      id: '/_authenticated/types'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof AuthenticatedTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transmissoes': {
      id: '/_authenticated/transmissoes'
      path: '/transmissoes'
      fullPath: '/transmissoes'
      preLoaderRoute: typeof AuthenticatedTransmissoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/oracoes': {
      id: '/_authenticated/oracoes'
      path: '/oracoes'
      fullPath: '/oracoes'
      preLoaderRoute: typeof AuthenticatedOracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membros': {
      id: '/_authenticated/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthenticatedMembrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/embed': {
      id: '/_authenticated/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof AuthenticatedEmbedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ebd': {
      id: '/_authenticated/ebd'
      path: '/ebd'
      fullPath: '/ebd'
      preLoaderRoute: typeof AuthenticatedEbdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devocional': {
      id: '/_authenticated/devocional'
      path: '/devocional'
      fullPath: '/devocional'
      preLoaderRoute: typeof AuthenticatedDevocionalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/celulas': {
      id: '/_authenticated/celulas'
      path: '/celulas'
      fullPath: '/celulas'
      preLoaderRoute: typeof AuthenticatedCelulasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/n/$slug/$postId': {
      id: '/n/$slug/$postId'
      path: '/$postId'
      fullPath: '/n/$slug/$postId'
      preLoaderRoute: typeof NSlugPostIdRouteImport
      parentRoute: typeof NSlugRoute
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ativopay-webhook': {
      id: '/api/public/ativopay-webhook'
      path: '/api/public/ativopay-webhook'
      fullPath: '/api/public/ativopay-webhook'
      preLoaderRoute: typeof ApiPublicAtivopayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketplace/$slug': {
      id: '/_authenticated/marketplace/$slug'
      path: '/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof AuthenticatedMarketplaceSlugRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/admin/test-data': {
      id: '/_authenticated/admin/test-data'
      path: '/admin/test-data'
      fullPath: '/admin/test-data'
      preLoaderRoute: typeof AuthenticatedAdminTestDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/instagram/callback': {
      id: '/api/public/instagram/callback'
      path: '/api/public/instagram/callback'
      fullPath: '/api/public/instagram/callback'
      preLoaderRoute: typeof ApiPublicInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/whatsapp-birthdays': {
      id: '/api/public/cron/whatsapp-birthdays'
      path: '/api/public/cron/whatsapp-birthdays'
      fullPath: '/api/public/cron/whatsapp-birthdays'
      preLoaderRoute: typeof ApiPublicCronWhatsappBirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/tithe-reminder': {
      id: '/api/public/cron/tithe-reminder'
      path: '/api/public/cron/tithe-reminder'
      fullPath: '/api/public/cron/tithe-reminder'
      preLoaderRoute: typeof ApiPublicCronTitheReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agenda/$siteId': {
      id: '/api/public/agenda/$siteId'
      path: '/api/public/agenda/$siteId'
      fullPath: '/api/public/agenda/$siteId'
      preLoaderRoute: typeof ApiPublicAgendaSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMarketplaceRouteChildren {
  AuthenticatedMarketplaceSlugRoute: typeof AuthenticatedMarketplaceSlugRoute
}

const AuthenticatedMarketplaceRouteChildren: AuthenticatedMarketplaceRouteChildren =
  {
    AuthenticatedMarketplaceSlugRoute: AuthenticatedMarketplaceSlugRoute,
  }

const AuthenticatedMarketplaceRouteWithChildren =
  AuthenticatedMarketplaceRoute._addFileChildren(
    AuthenticatedMarketplaceRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCelulasRoute: typeof AuthenticatedCelulasRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevocionalRoute: typeof AuthenticatedDevocionalRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEbdRoute: typeof AuthenticatedEbdRoute
  AuthenticatedEmbedRoute: typeof AuthenticatedEmbedRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRouteWithChildren
  AuthenticatedMembrosRoute: typeof AuthenticatedMembrosRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOracoesRoute: typeof AuthenticatedOracoesRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransmissoesRoute: typeof AuthenticatedTransmissoesRoute
  AuthenticatedTypesRoute: typeof AuthenticatedTypesRoute
  AuthenticatedVisitantesRoute: typeof AuthenticatedVisitantesRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminTestDataRoute: typeof AuthenticatedAdminTestDataRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCelulasRoute: AuthenticatedCelulasRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevocionalRoute: AuthenticatedDevocionalRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEbdRoute: AuthenticatedEbdRoute,
  AuthenticatedEmbedRoute: AuthenticatedEmbedRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRouteWithChildren,
  AuthenticatedMembrosRoute: AuthenticatedMembrosRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOracoesRoute: AuthenticatedOracoesRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransmissoesRoute: AuthenticatedTransmissoesRoute,
  AuthenticatedTypesRoute: AuthenticatedTypesRoute,
  AuthenticatedVisitantesRoute: AuthenticatedVisitantesRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminTestDataRoute: AuthenticatedAdminTestDataRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NSlugRouteChildren {
  NSlugPostIdRoute: typeof NSlugPostIdRoute
}

const NSlugRouteChildren: NSlugRouteChildren = {
  NSlugPostIdRoute: NSlugPostIdRoute,
}

const NSlugRouteWithChildren = NSlugRoute._addFileChildren(NSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ASiteIdRoute: ASiteIdRoute,
  CMemberIdRoute: CMemberIdRoute,
  CheckinSessionIdRoute: CheckinSessionIdRoute,
  DSlugRoute: DSlugRoute,
  ESlugRoute: ESlugRoute,
  EnderecosSlugRoute: EnderecosSlugRoute,
  EventosSlugRoute: EventosSlugRoute,
  NSlugRoute: NSlugRouteWithChildren,
  OSiteIdRoute: OSiteIdRoute,
  ReciboDonationIdRoute: ReciboDonationIdRoute,
  VSiteIdRoute: VSiteIdRoute,
  ApiPublicAtivopayWebhookRoute: ApiPublicAtivopayWebhookRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicAgendaSiteIdRoute: ApiPublicAgendaSiteIdRoute,
  ApiPublicCronTitheReminderRoute: ApiPublicCronTitheReminderRoute,
  ApiPublicCronWhatsappBirthdaysRoute: ApiPublicCronWhatsappBirthdaysRoute,
  ApiPublicInstagramCallbackRoute: ApiPublicInstagramCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
