/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VSiteIdRouteImport } from './routes/v.$siteId'
import { Route as ReciboDonationIdRouteImport } from './routes/recibo.$donationId'
import { Route as ProtocoloIdRouteImport } from './routes/protocolo.$id'
import { Route as PpSiteIdRouteImport } from './routes/pp.$siteId'
import { Route as OSiteIdRouteImport } from './routes/o.$siteId'
import { Route as NSlugRouteImport } from './routes/n.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as EnderecosSlugRouteImport } from './routes/enderecos.$slug'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as DecSiteIdRouteImport } from './routes/dec.$siteId'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as CheckinSessionIdRouteImport } from './routes/checkin.$sessionId'
import { Route as CertIdRouteImport } from './routes/cert.$id'
import { Route as CMemberIdRouteImport } from './routes/c.$memberId'
import { Route as ASiteIdRouteImport } from './routes/a.$siteId'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated.whatsapp'
import { Route as AuthenticatedVisitantesRouteImport } from './routes/_authenticated.visitantes'
import { Route as AuthenticatedTypesRouteImport } from './routes/_authenticated.types'
import { Route as AuthenticatedTransmissoesRouteImport } from './routes/_authenticated.transmissoes'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSecretariaRouteImport } from './routes/_authenticated.secretaria'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated.reservas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedPrivacidadeRouteImport } from './routes/_authenticated.privacidade'
import { Route as AuthenticatedPoliticaPrivacidadeRouteImport } from './routes/_authenticated.politica-privacidade'
import { Route as AuthenticatedPatrimonioRouteImport } from './routes/_authenticated.patrimonio'
import { Route as AuthenticatedOracoesRouteImport } from './routes/_authenticated.oracoes'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedMinisteriosRouteImport } from './routes/_authenticated.ministerios'
import { Route as AuthenticatedMembrosRouteImport } from './routes/_authenticated.membros'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated.marketplace'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated.locations'
import { Route as AuthenticatedLivroCaixaRouteImport } from './routes/_authenticated.livro-caixa'
import { Route as AuthenticatedJornadaEspiritualRouteImport } from './routes/_authenticated.jornada-espiritual'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated.hub'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated.finances'
import { Route as AuthenticatedFamiliasRouteImport } from './routes/_authenticated.familias'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated.eventos'
import { Route as AuthenticatedEscalasRouteImport } from './routes/_authenticated.escalas'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated.equipe'
import { Route as AuthenticatedEmbedRouteImport } from './routes/_authenticated.embed'
import { Route as AuthenticatedEbdRouteImport } from './routes/_authenticated.ebd'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated.documentos'
import { Route as AuthenticatedDevocionalRouteImport } from './routes/_authenticated.devocional'
import { Route as AuthenticatedDecisoesRouteImport } from './routes/_authenticated.decisoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedContasBancariasRouteImport } from './routes/_authenticated.contas-bancarias'
import { Route as AuthenticatedCongregacoesRouteImport } from './routes/_authenticated.congregacoes'
import { Route as AuthenticatedCheckinInfantilRouteImport } from './routes/_authenticated.checkin-infantil'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated.checkin'
import { Route as AuthenticatedCelulasRouteImport } from './routes/_authenticated.celulas'
import { Route as AuthenticatedCampanhasRouteImport } from './routes/_authenticated.campanhas'
import { Route as AuthenticatedBoletimRouteImport } from './routes/_authenticated.boletim'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedAusenciasRouteImport } from './routes/_authenticated.ausencias'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated.agenda'
import { Route as AuthenticatedAcaoSocialRouteImport } from './routes/_authenticated.acao-social'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as NSlugPostIdRouteImport } from './routes/n.$slug.$postId'
import { Route as ManifestSiteIdJsonRouteImport } from './routes/manifest.$siteId.json'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api.public.whatsapp-webhook'
import { Route as ApiPublicWhatsappOptOutRouteImport } from './routes/api.public.whatsapp-opt-out'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api.public.mercadopago-webhook'
import { Route as AuthenticatedMarketplaceSlugRouteImport } from './routes/_authenticated.marketplace.$slug'
import { Route as AuthenticatedAdminWhatsappRouteImport } from './routes/_authenticated.admin.whatsapp'
import { Route as AuthenticatedAdminTestDataRouteImport } from './routes/_authenticated.admin.test-data'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated.admin.products'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated.admin.payments'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated.admin.feedback'
import { Route as AuthenticatedAdminDomainsRouteImport } from './routes/_authenticated.admin.domains'
import { Route as ApiPublicInstagramCallbackRouteImport } from './routes/api.public.instagram.callback'
import { Route as ApiPublicCronWhatsappDispatchRouteImport } from './routes/api.public.cron.whatsapp-dispatch'
import { Route as ApiPublicCronWhatsappBirthdaysRouteImport } from './routes/api.public.cron.whatsapp-birthdays'
import { Route as ApiPublicCronTitheReminderRouteImport } from './routes/api.public.cron.tithe-reminder'
import { Route as ApiPublicAgendaSiteIdRouteImport } from './routes/api.public.agenda.$siteId'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VSiteIdRoute = VSiteIdRouteImport.update({
  id: '/v/$siteId',
  path: '/v/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReciboDonationIdRoute = ReciboDonationIdRouteImport.update({
  id: '/recibo/$donationId',
  path: '/recibo/$donationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocoloIdRoute = ProtocoloIdRouteImport.update({
  id: '/protocolo/$id',
  path: '/protocolo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PpSiteIdRoute = PpSiteIdRouteImport.update({
  id: '/pp/$siteId',
  path: '/pp/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const OSiteIdRoute = OSiteIdRouteImport.update({
  id: '/o/$siteId',
  path: '/o/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnderecosSlugRoute = EnderecosSlugRouteImport.update({
  id: '/enderecos/$slug',
  path: '/enderecos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DecSiteIdRoute = DecSiteIdRouteImport.update({
  id: '/dec/$siteId',
  path: '/dec/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinSessionIdRoute = CheckinSessionIdRouteImport.update({
  id: '/checkin/$sessionId',
  path: '/checkin/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CertIdRoute = CertIdRouteImport.update({
  id: '/cert/$id',
  path: '/cert/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CMemberIdRoute = CMemberIdRouteImport.update({
  id: '/c/$memberId',
  path: '/c/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const ASiteIdRoute = ASiteIdRouteImport.update({
  id: '/a/$siteId',
  path: '/a/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitantesRoute = AuthenticatedVisitantesRouteImport.update({
  id: '/visitantes',
  path: '/visitantes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTypesRoute = AuthenticatedTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransmissoesRoute =
  AuthenticatedTransmissoesRouteImport.update({
    id: '/transmissoes',
    path: '/transmissoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecretariaRoute = AuthenticatedSecretariaRouteImport.update({
  id: '/secretaria',
  path: '/secretaria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrivacidadeRoute =
  AuthenticatedPrivacidadeRouteImport.update({
    id: '/privacidade',
    path: '/privacidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPoliticaPrivacidadeRoute =
  AuthenticatedPoliticaPrivacidadeRouteImport.update({
    id: '/politica-privacidade',
    path: '/politica-privacidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatrimonioRoute = AuthenticatedPatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOracoesRoute = AuthenticatedOracoesRouteImport.update({
  id: '/oracoes',
  path: '/oracoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinisteriosRoute =
  AuthenticatedMinisteriosRouteImport.update({
    id: '/ministerios',
    path: '/ministerios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembrosRoute = AuthenticatedMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLivroCaixaRoute = AuthenticatedLivroCaixaRouteImport.update({
  id: '/livro-caixa',
  path: '/livro-caixa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJornadaEspiritualRoute =
  AuthenticatedJornadaEspiritualRouteImport.update({
    id: '/jornada-espiritual',
    path: '/jornada-espiritual',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFamiliasRoute = AuthenticatedFamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEscalasRoute = AuthenticatedEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmbedRoute = AuthenticatedEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEbdRoute = AuthenticatedEbdRouteImport.update({
  id: '/ebd',
  path: '/ebd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevocionalRoute = AuthenticatedDevocionalRouteImport.update({
  id: '/devocional',
  path: '/devocional',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDecisoesRoute = AuthenticatedDecisoesRouteImport.update({
  id: '/decisoes',
  path: '/decisoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContasBancariasRoute =
  AuthenticatedContasBancariasRouteImport.update({
    id: '/contas-bancarias',
    path: '/contas-bancarias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCongregacoesRoute =
  AuthenticatedCongregacoesRouteImport.update({
    id: '/congregacoes',
    path: '/congregacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckinInfantilRoute =
  AuthenticatedCheckinInfantilRouteImport.update({
    id: '/checkin-infantil',
    path: '/checkin-infantil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCelulasRoute = AuthenticatedCelulasRouteImport.update({
  id: '/celulas',
  path: '/celulas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampanhasRoute = AuthenticatedCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBoletimRoute = AuthenticatedBoletimRouteImport.update({
  id: '/boletim',
  path: '/boletim',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAusenciasRoute = AuthenticatedAusenciasRouteImport.update({
  id: '/ausencias',
  path: '/ausencias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcaoSocialRoute = AuthenticatedAcaoSocialRouteImport.update({
  id: '/acao-social',
  path: '/acao-social',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const NSlugPostIdRoute = NSlugPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => NSlugRoute,
} as any)
const ManifestSiteIdJsonRoute = ManifestSiteIdJsonRouteImport.update({
  id: '/manifest/$siteId/json',
  path: '/manifest/$siteId/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappOptOutRoute = ApiPublicWhatsappOptOutRouteImport.update({
  id: '/api/public/whatsapp-opt-out',
  path: '/api/public/whatsapp-opt-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMarketplaceSlugRoute =
  AuthenticatedMarketplaceSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedAdminWhatsappRoute =
  AuthenticatedAdminWhatsappRouteImport.update({
    id: '/admin/whatsapp',
    path: '/admin/whatsapp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTestDataRoute =
  AuthenticatedAdminTestDataRouteImport.update({
    id: '/admin/test-data',
    path: '/admin/test-data',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/admin/feedback',
    path: '/admin/feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDomainsRoute =
  AuthenticatedAdminDomainsRouteImport.update({
    id: '/admin/domains',
    path: '/admin/domains',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicInstagramCallbackRoute =
  ApiPublicInstagramCallbackRouteImport.update({
    id: '/api/public/instagram/callback',
    path: '/api/public/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronWhatsappDispatchRoute =
  ApiPublicCronWhatsappDispatchRouteImport.update({
    id: '/api/public/cron/whatsapp-dispatch',
    path: '/api/public/cron/whatsapp-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronWhatsappBirthdaysRoute =
  ApiPublicCronWhatsappBirthdaysRouteImport.update({
    id: '/api/public/cron/whatsapp-birthdays',
    path: '/api/public/cron/whatsapp-birthdays',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTitheReminderRoute =
  ApiPublicCronTitheReminderRouteImport.update({
    id: '/api/public/cron/tithe-reminder',
    path: '/api/public/cron/tithe-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgendaSiteIdRoute = ApiPublicAgendaSiteIdRouteImport.update({
  id: '/api/public/agenda/$siteId',
  path: '/api/public/agenda/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/update-password': typeof UpdatePasswordRoute
  '/acao-social': typeof AuthenticatedAcaoSocialRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/boletim': typeof AuthenticatedBoletimRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/celulas': typeof AuthenticatedCelulasRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/checkin-infantil': typeof AuthenticatedCheckinInfantilRoute
  '/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decisoes': typeof AuthenticatedDecisoesRoute
  '/devocional': typeof AuthenticatedDevocionalRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/ebd': typeof AuthenticatedEbdRoute
  '/embed': typeof AuthenticatedEmbedRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/escalas': typeof AuthenticatedEscalasRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/familias': typeof AuthenticatedFamiliasRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/hub': typeof AuthenticatedHubRoute
  '/jornada-espiritual': typeof AuthenticatedJornadaEspiritualRoute
  '/livro-caixa': typeof AuthenticatedLivroCaixaRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/membros': typeof AuthenticatedMembrosRoute
  '/ministerios': typeof AuthenticatedMinisteriosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/oracoes': typeof AuthenticatedOracoesRoute
  '/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/politica-privacidade': typeof AuthenticatedPoliticaPrivacidadeRoute
  '/privacidade': typeof AuthenticatedPrivacidadeRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/secretaria': typeof AuthenticatedSecretariaRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transmissoes': typeof AuthenticatedTransmissoesRoute
  '/types': typeof AuthenticatedTypesRoute
  '/visitantes': typeof AuthenticatedVisitantesRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/a/$siteId': typeof ASiteIdRoute
  '/c/$memberId': typeof CMemberIdRoute
  '/cert/$id': typeof CertIdRoute
  '/checkin/$sessionId': typeof CheckinSessionIdRoute
  '/d/$slug': typeof DSlugRoute
  '/dec/$siteId': typeof DecSiteIdRoute
  '/e/$slug': typeof ESlugRoute
  '/enderecos/$slug': typeof EnderecosSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/n/$slug': typeof NSlugRouteWithChildren
  '/o/$siteId': typeof OSiteIdRoute
  '/pp/$siteId': typeof PpSiteIdRoute
  '/protocolo/$id': typeof ProtocoloIdRoute
  '/recibo/$donationId': typeof ReciboDonationIdRoute
  '/v/$siteId': typeof VSiteIdRoute
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/test-data': typeof AuthenticatedAdminTestDataRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/marketplace/$slug': typeof AuthenticatedMarketplaceSlugRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/whatsapp-opt-out': typeof ApiPublicWhatsappOptOutRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/manifest/$siteId/json': typeof ManifestSiteIdJsonRoute
  '/n/$slug/$postId': typeof NSlugPostIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/agenda/$siteId': typeof ApiPublicAgendaSiteIdRoute
  '/api/public/cron/tithe-reminder': typeof ApiPublicCronTitheReminderRoute
  '/api/public/cron/whatsapp-birthdays': typeof ApiPublicCronWhatsappBirthdaysRoute
  '/api/public/cron/whatsapp-dispatch': typeof ApiPublicCronWhatsappDispatchRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/update-password': typeof UpdatePasswordRoute
  '/acao-social': typeof AuthenticatedAcaoSocialRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/boletim': typeof AuthenticatedBoletimRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/celulas': typeof AuthenticatedCelulasRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/checkin-infantil': typeof AuthenticatedCheckinInfantilRoute
  '/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decisoes': typeof AuthenticatedDecisoesRoute
  '/devocional': typeof AuthenticatedDevocionalRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/ebd': typeof AuthenticatedEbdRoute
  '/embed': typeof AuthenticatedEmbedRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/escalas': typeof AuthenticatedEscalasRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/familias': typeof AuthenticatedFamiliasRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/hub': typeof AuthenticatedHubRoute
  '/jornada-espiritual': typeof AuthenticatedJornadaEspiritualRoute
  '/livro-caixa': typeof AuthenticatedLivroCaixaRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/membros': typeof AuthenticatedMembrosRoute
  '/ministerios': typeof AuthenticatedMinisteriosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/oracoes': typeof AuthenticatedOracoesRoute
  '/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/politica-privacidade': typeof AuthenticatedPoliticaPrivacidadeRoute
  '/privacidade': typeof AuthenticatedPrivacidadeRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/secretaria': typeof AuthenticatedSecretariaRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transmissoes': typeof AuthenticatedTransmissoesRoute
  '/types': typeof AuthenticatedTypesRoute
  '/visitantes': typeof AuthenticatedVisitantesRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/a/$siteId': typeof ASiteIdRoute
  '/c/$memberId': typeof CMemberIdRoute
  '/cert/$id': typeof CertIdRoute
  '/checkin/$sessionId': typeof CheckinSessionIdRoute
  '/d/$slug': typeof DSlugRoute
  '/dec/$siteId': typeof DecSiteIdRoute
  '/e/$slug': typeof ESlugRoute
  '/enderecos/$slug': typeof EnderecosSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/n/$slug': typeof NSlugRouteWithChildren
  '/o/$siteId': typeof OSiteIdRoute
  '/pp/$siteId': typeof PpSiteIdRoute
  '/protocolo/$id': typeof ProtocoloIdRoute
  '/recibo/$donationId': typeof ReciboDonationIdRoute
  '/v/$siteId': typeof VSiteIdRoute
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/test-data': typeof AuthenticatedAdminTestDataRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/marketplace/$slug': typeof AuthenticatedMarketplaceSlugRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/whatsapp-opt-out': typeof ApiPublicWhatsappOptOutRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/manifest/$siteId/json': typeof ManifestSiteIdJsonRoute
  '/n/$slug/$postId': typeof NSlugPostIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/agenda/$siteId': typeof ApiPublicAgendaSiteIdRoute
  '/api/public/cron/tithe-reminder': typeof ApiPublicCronTitheReminderRoute
  '/api/public/cron/whatsapp-birthdays': typeof ApiPublicCronWhatsappBirthdaysRoute
  '/api/public/cron/whatsapp-dispatch': typeof ApiPublicCronWhatsappDispatchRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/acao-social': typeof AuthenticatedAcaoSocialRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/ausencias': typeof AuthenticatedAusenciasRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/boletim': typeof AuthenticatedBoletimRoute
  '/_authenticated/campanhas': typeof AuthenticatedCampanhasRoute
  '/_authenticated/celulas': typeof AuthenticatedCelulasRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/checkin-infantil': typeof AuthenticatedCheckinInfantilRoute
  '/_authenticated/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/_authenticated/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/decisoes': typeof AuthenticatedDecisoesRoute
  '/_authenticated/devocional': typeof AuthenticatedDevocionalRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/ebd': typeof AuthenticatedEbdRoute
  '/_authenticated/embed': typeof AuthenticatedEmbedRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/escalas': typeof AuthenticatedEscalasRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/familias': typeof AuthenticatedFamiliasRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/jornada-espiritual': typeof AuthenticatedJornadaEspiritualRoute
  '/_authenticated/livro-caixa': typeof AuthenticatedLivroCaixaRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/_authenticated/membros': typeof AuthenticatedMembrosRoute
  '/_authenticated/ministerios': typeof AuthenticatedMinisteriosRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/oracoes': typeof AuthenticatedOracoesRoute
  '/_authenticated/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/_authenticated/politica-privacidade': typeof AuthenticatedPoliticaPrivacidadeRoute
  '/_authenticated/privacidade': typeof AuthenticatedPrivacidadeRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
  '/_authenticated/secretaria': typeof AuthenticatedSecretariaRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transmissoes': typeof AuthenticatedTransmissoesRoute
  '/_authenticated/types': typeof AuthenticatedTypesRoute
  '/_authenticated/visitantes': typeof AuthenticatedVisitantesRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/a/$siteId': typeof ASiteIdRoute
  '/c/$memberId': typeof CMemberIdRoute
  '/cert/$id': typeof CertIdRoute
  '/checkin/$sessionId': typeof CheckinSessionIdRoute
  '/d/$slug': typeof DSlugRoute
  '/dec/$siteId': typeof DecSiteIdRoute
  '/e/$slug': typeof ESlugRoute
  '/enderecos/$slug': typeof EnderecosSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/n/$slug': typeof NSlugRouteWithChildren
  '/o/$siteId': typeof OSiteIdRoute
  '/pp/$siteId': typeof PpSiteIdRoute
  '/protocolo/$id': typeof ProtocoloIdRoute
  '/recibo/$donationId': typeof ReciboDonationIdRoute
  '/v/$siteId': typeof VSiteIdRoute
  '/_authenticated/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/test-data': typeof AuthenticatedAdminTestDataRoute
  '/_authenticated/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/_authenticated/marketplace/$slug': typeof AuthenticatedMarketplaceSlugRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/whatsapp-opt-out': typeof ApiPublicWhatsappOptOutRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/manifest/$siteId/json': typeof ManifestSiteIdJsonRoute
  '/n/$slug/$postId': typeof NSlugPostIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/agenda/$siteId': typeof ApiPublicAgendaSiteIdRoute
  '/api/public/cron/tithe-reminder': typeof ApiPublicCronTitheReminderRoute
  '/api/public/cron/whatsapp-birthdays': typeof ApiPublicCronWhatsappBirthdaysRoute
  '/api/public/cron/whatsapp-dispatch': typeof ApiPublicCronWhatsappDispatchRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/login'
    | '/update-password'
    | '/acao-social'
    | '/agenda'
    | '/ausencias'
    | '/billing'
    | '/boletim'
    | '/campanhas'
    | '/celulas'
    | '/checkin'
    | '/checkin-infantil'
    | '/congregacoes'
    | '/contas-bancarias'
    | '/dashboard'
    | '/decisoes'
    | '/devocional'
    | '/documentos'
    | '/ebd'
    | '/embed'
    | '/equipe'
    | '/escalas'
    | '/eventos'
    | '/familias'
    | '/finances'
    | '/hub'
    | '/jornada-espiritual'
    | '/livro-caixa'
    | '/locations'
    | '/marketplace'
    | '/membros'
    | '/ministerios'
    | '/onboarding'
    | '/oracoes'
    | '/patrimonio'
    | '/politica-privacidade'
    | '/privacidade'
    | '/relatorios'
    | '/reservas'
    | '/secretaria'
    | '/settings'
    | '/transmissoes'
    | '/types'
    | '/visitantes'
    | '/whatsapp'
    | '/a/$siteId'
    | '/c/$memberId'
    | '/cert/$id'
    | '/checkin/$sessionId'
    | '/d/$slug'
    | '/dec/$siteId'
    | '/e/$slug'
    | '/enderecos/$slug'
    | '/eventos/$slug'
    | '/n/$slug'
    | '/o/$siteId'
    | '/pp/$siteId'
    | '/protocolo/$id'
    | '/recibo/$donationId'
    | '/v/$siteId'
    | '/admin/domains'
    | '/admin/feedback'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/test-data'
    | '/admin/whatsapp'
    | '/marketplace/$slug'
    | '/api/public/mercadopago-webhook'
    | '/api/public/whatsapp-opt-out'
    | '/api/public/whatsapp-webhook'
    | '/manifest/$siteId/json'
    | '/n/$slug/$postId'
    | '/admin/'
    | '/api/public/agenda/$siteId'
    | '/api/public/cron/tithe-reminder'
    | '/api/public/cron/whatsapp-birthdays'
    | '/api/public/cron/whatsapp-dispatch'
    | '/api/public/instagram/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/update-password'
    | '/acao-social'
    | '/agenda'
    | '/ausencias'
    | '/billing'
    | '/boletim'
    | '/campanhas'
    | '/celulas'
    | '/checkin'
    | '/checkin-infantil'
    | '/congregacoes'
    | '/contas-bancarias'
    | '/dashboard'
    | '/decisoes'
    | '/devocional'
    | '/documentos'
    | '/ebd'
    | '/embed'
    | '/equipe'
    | '/escalas'
    | '/eventos'
    | '/familias'
    | '/finances'
    | '/hub'
    | '/jornada-espiritual'
    | '/livro-caixa'
    | '/locations'
    | '/marketplace'
    | '/membros'
    | '/ministerios'
    | '/onboarding'
    | '/oracoes'
    | '/patrimonio'
    | '/politica-privacidade'
    | '/privacidade'
    | '/relatorios'
    | '/reservas'
    | '/secretaria'
    | '/settings'
    | '/transmissoes'
    | '/types'
    | '/visitantes'
    | '/whatsapp'
    | '/a/$siteId'
    | '/c/$memberId'
    | '/cert/$id'
    | '/checkin/$sessionId'
    | '/d/$slug'
    | '/dec/$siteId'
    | '/e/$slug'
    | '/enderecos/$slug'
    | '/eventos/$slug'
    | '/n/$slug'
    | '/o/$siteId'
    | '/pp/$siteId'
    | '/protocolo/$id'
    | '/recibo/$donationId'
    | '/v/$siteId'
    | '/admin/domains'
    | '/admin/feedback'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/test-data'
    | '/admin/whatsapp'
    | '/marketplace/$slug'
    | '/api/public/mercadopago-webhook'
    | '/api/public/whatsapp-opt-out'
    | '/api/public/whatsapp-webhook'
    | '/manifest/$siteId/json'
    | '/n/$slug/$postId'
    | '/admin'
    | '/api/public/agenda/$siteId'
    | '/api/public/cron/tithe-reminder'
    | '/api/public/cron/whatsapp-birthdays'
    | '/api/public/cron/whatsapp-dispatch'
    | '/api/public/instagram/callback'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/login'
    | '/update-password'
    | '/_authenticated/acao-social'
    | '/_authenticated/agenda'
    | '/_authenticated/ausencias'
    | '/_authenticated/billing'
    | '/_authenticated/boletim'
    | '/_authenticated/campanhas'
    | '/_authenticated/celulas'
    | '/_authenticated/checkin'
    | '/_authenticated/checkin-infantil'
    | '/_authenticated/congregacoes'
    | '/_authenticated/contas-bancarias'
    | '/_authenticated/dashboard'
    | '/_authenticated/decisoes'
    | '/_authenticated/devocional'
    | '/_authenticated/documentos'
    | '/_authenticated/ebd'
    | '/_authenticated/embed'
    | '/_authenticated/equipe'
    | '/_authenticated/escalas'
    | '/_authenticated/eventos'
    | '/_authenticated/familias'
    | '/_authenticated/finances'
    | '/_authenticated/hub'
    | '/_authenticated/jornada-espiritual'
    | '/_authenticated/livro-caixa'
    | '/_authenticated/locations'
    | '/_authenticated/marketplace'
    | '/_authenticated/membros'
    | '/_authenticated/ministerios'
    | '/_authenticated/onboarding'
    | '/_authenticated/oracoes'
    | '/_authenticated/patrimonio'
    | '/_authenticated/politica-privacidade'
    | '/_authenticated/privacidade'
    | '/_authenticated/relatorios'
    | '/_authenticated/reservas'
    | '/_authenticated/secretaria'
    | '/_authenticated/settings'
    | '/_authenticated/transmissoes'
    | '/_authenticated/types'
    | '/_authenticated/visitantes'
    | '/_authenticated/whatsapp'
    | '/a/$siteId'
    | '/c/$memberId'
    | '/cert/$id'
    | '/checkin/$sessionId'
    | '/d/$slug'
    | '/dec/$siteId'
    | '/e/$slug'
    | '/enderecos/$slug'
    | '/eventos/$slug'
    | '/n/$slug'
    | '/o/$siteId'
    | '/pp/$siteId'
    | '/protocolo/$id'
    | '/recibo/$donationId'
    | '/v/$siteId'
    | '/_authenticated/admin/domains'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/test-data'
    | '/_authenticated/admin/whatsapp'
    | '/_authenticated/marketplace/$slug'
    | '/api/public/mercadopago-webhook'
    | '/api/public/whatsapp-opt-out'
    | '/api/public/whatsapp-webhook'
    | '/manifest/$siteId/json'
    | '/n/$slug/$postId'
    | '/_authenticated/admin/'
    | '/api/public/agenda/$siteId'
    | '/api/public/cron/tithe-reminder'
    | '/api/public/cron/whatsapp-birthdays'
    | '/api/public/cron/whatsapp-dispatch'
    | '/api/public/instagram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  ASiteIdRoute: typeof ASiteIdRoute
  CMemberIdRoute: typeof CMemberIdRoute
  CertIdRoute: typeof CertIdRoute
  CheckinSessionIdRoute: typeof CheckinSessionIdRoute
  DSlugRoute: typeof DSlugRoute
  DecSiteIdRoute: typeof DecSiteIdRoute
  ESlugRoute: typeof ESlugRoute
  EnderecosSlugRoute: typeof EnderecosSlugRoute
  EventosSlugRoute: typeof EventosSlugRoute
  NSlugRoute: typeof NSlugRouteWithChildren
  OSiteIdRoute: typeof OSiteIdRoute
  PpSiteIdRoute: typeof PpSiteIdRoute
  ProtocoloIdRoute: typeof ProtocoloIdRoute
  ReciboDonationIdRoute: typeof ReciboDonationIdRoute
  VSiteIdRoute: typeof VSiteIdRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicWhatsappOptOutRoute: typeof ApiPublicWhatsappOptOutRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ManifestSiteIdJsonRoute: typeof ManifestSiteIdJsonRoute
  ApiPublicAgendaSiteIdRoute: typeof ApiPublicAgendaSiteIdRoute
  ApiPublicCronTitheReminderRoute: typeof ApiPublicCronTitheReminderRoute
  ApiPublicCronWhatsappBirthdaysRoute: typeof ApiPublicCronWhatsappBirthdaysRoute
  ApiPublicCronWhatsappDispatchRoute: typeof ApiPublicCronWhatsappDispatchRoute
  ApiPublicInstagramCallbackRoute: typeof ApiPublicInstagramCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$siteId': {
      id: '/v/$siteId'
      path: '/v/$siteId'
      fullPath: '/v/$siteId'
      preLoaderRoute: typeof VSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibo/$donationId': {
      id: '/recibo/$donationId'
      path: '/recibo/$donationId'
      fullPath: '/recibo/$donationId'
      preLoaderRoute: typeof ReciboDonationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo/$id': {
      id: '/protocolo/$id'
      path: '/protocolo/$id'
      fullPath: '/protocolo/$id'
      preLoaderRoute: typeof ProtocoloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pp/$siteId': {
      id: '/pp/$siteId'
      path: '/pp/$siteId'
      fullPath: '/pp/$siteId'
      preLoaderRoute: typeof PpSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$siteId': {
      id: '/o/$siteId'
      path: '/o/$siteId'
      fullPath: '/o/$siteId'
      preLoaderRoute: typeof OSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enderecos/$slug': {
      id: '/enderecos/$slug'
      path: '/enderecos/$slug'
      fullPath: '/enderecos/$slug'
      preLoaderRoute: typeof EnderecosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dec/$siteId': {
      id: '/dec/$siteId'
      path: '/dec/$siteId'
      fullPath: '/dec/$siteId'
      preLoaderRoute: typeof DecSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$sessionId': {
      id: '/checkin/$sessionId'
      path: '/checkin/$sessionId'
      fullPath: '/checkin/$sessionId'
      preLoaderRoute: typeof CheckinSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cert/$id': {
      id: '/cert/$id'
      path: '/cert/$id'
      fullPath: '/cert/$id'
      preLoaderRoute: typeof CertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$memberId': {
      id: '/c/$memberId'
      path: '/c/$memberId'
      fullPath: '/c/$memberId'
      preLoaderRoute: typeof CMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$siteId': {
      id: '/a/$siteId'
      path: '/a/$siteId'
      fullPath: '/a/$siteId'
      preLoaderRoute: typeof ASiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visitantes': {
      id: '/_authenticated/visitantes'
      path: '/visitantes'
      fullPath: '/visitantes'
      preLoaderRoute: typeof AuthenticatedVisitantesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/types': {
      id: '/_authenticated/types'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof AuthenticatedTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transmissoes': {
      id: '/_authenticated/transmissoes'
      path: '/transmissoes'
      fullPath: '/transmissoes'
      preLoaderRoute: typeof AuthenticatedTransmissoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secretaria': {
      id: '/_authenticated/secretaria'
      path: '/secretaria'
      fullPath: '/secretaria'
      preLoaderRoute: typeof AuthenticatedSecretariaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/privacidade': {
      id: '/_authenticated/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof AuthenticatedPrivacidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/politica-privacidade': {
      id: '/_authenticated/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof AuthenticatedPoliticaPrivacidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patrimonio': {
      id: '/_authenticated/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof AuthenticatedPatrimonioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/oracoes': {
      id: '/_authenticated/oracoes'
      path: '/oracoes'
      fullPath: '/oracoes'
      preLoaderRoute: typeof AuthenticatedOracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ministerios': {
      id: '/_authenticated/ministerios'
      path: '/ministerios'
      fullPath: '/ministerios'
      preLoaderRoute: typeof AuthenticatedMinisteriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membros': {
      id: '/_authenticated/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthenticatedMembrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/livro-caixa': {
      id: '/_authenticated/livro-caixa'
      path: '/livro-caixa'
      fullPath: '/livro-caixa'
      preLoaderRoute: typeof AuthenticatedLivroCaixaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jornada-espiritual': {
      id: '/_authenticated/jornada-espiritual'
      path: '/jornada-espiritual'
      fullPath: '/jornada-espiritual'
      preLoaderRoute: typeof AuthenticatedJornadaEspiritualRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/familias': {
      id: '/_authenticated/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof AuthenticatedFamiliasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/escalas': {
      id: '/_authenticated/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof AuthenticatedEscalasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/embed': {
      id: '/_authenticated/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof AuthenticatedEmbedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ebd': {
      id: '/_authenticated/ebd'
      path: '/ebd'
      fullPath: '/ebd'
      preLoaderRoute: typeof AuthenticatedEbdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devocional': {
      id: '/_authenticated/devocional'
      path: '/devocional'
      fullPath: '/devocional'
      preLoaderRoute: typeof AuthenticatedDevocionalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/decisoes': {
      id: '/_authenticated/decisoes'
      path: '/decisoes'
      fullPath: '/decisoes'
      preLoaderRoute: typeof AuthenticatedDecisoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-bancarias': {
      id: '/_authenticated/contas-bancarias'
      path: '/contas-bancarias'
      fullPath: '/contas-bancarias'
      preLoaderRoute: typeof AuthenticatedContasBancariasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/congregacoes': {
      id: '/_authenticated/congregacoes'
      path: '/congregacoes'
      fullPath: '/congregacoes'
      preLoaderRoute: typeof AuthenticatedCongregacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkin-infantil': {
      id: '/_authenticated/checkin-infantil'
      path: '/checkin-infantil'
      fullPath: '/checkin-infantil'
      preLoaderRoute: typeof AuthenticatedCheckinInfantilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/celulas': {
      id: '/_authenticated/celulas'
      path: '/celulas'
      fullPath: '/celulas'
      preLoaderRoute: typeof AuthenticatedCelulasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campanhas': {
      id: '/_authenticated/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AuthenticatedCampanhasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/boletim': {
      id: '/_authenticated/boletim'
      path: '/boletim'
      fullPath: '/boletim'
      preLoaderRoute: typeof AuthenticatedBoletimRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ausencias': {
      id: '/_authenticated/ausencias'
      path: '/ausencias'
      fullPath: '/ausencias'
      preLoaderRoute: typeof AuthenticatedAusenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acao-social': {
      id: '/_authenticated/acao-social'
      path: '/acao-social'
      fullPath: '/acao-social'
      preLoaderRoute: typeof AuthenticatedAcaoSocialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/n/$slug/$postId': {
      id: '/n/$slug/$postId'
      path: '/$postId'
      fullPath: '/n/$slug/$postId'
      preLoaderRoute: typeof NSlugPostIdRouteImport
      parentRoute: typeof NSlugRoute
    }
    '/manifest/$siteId/json': {
      id: '/manifest/$siteId/json'
      path: '/manifest/$siteId/json'
      fullPath: '/manifest/$siteId/json'
      preLoaderRoute: typeof ManifestSiteIdJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-opt-out': {
      id: '/api/public/whatsapp-opt-out'
      path: '/api/public/whatsapp-opt-out'
      fullPath: '/api/public/whatsapp-opt-out'
      preLoaderRoute: typeof ApiPublicWhatsappOptOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketplace/$slug': {
      id: '/_authenticated/marketplace/$slug'
      path: '/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof AuthenticatedMarketplaceSlugRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/admin/whatsapp': {
      id: '/_authenticated/admin/whatsapp'
      path: '/admin/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/test-data': {
      id: '/_authenticated/admin/test-data'
      path: '/admin/test-data'
      fullPath: '/admin/test-data'
      preLoaderRoute: typeof AuthenticatedAdminTestDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/domains': {
      id: '/_authenticated/admin/domains'
      path: '/admin/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AuthenticatedAdminDomainsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/instagram/callback': {
      id: '/api/public/instagram/callback'
      path: '/api/public/instagram/callback'
      fullPath: '/api/public/instagram/callback'
      preLoaderRoute: typeof ApiPublicInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/whatsapp-dispatch': {
      id: '/api/public/cron/whatsapp-dispatch'
      path: '/api/public/cron/whatsapp-dispatch'
      fullPath: '/api/public/cron/whatsapp-dispatch'
      preLoaderRoute: typeof ApiPublicCronWhatsappDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/whatsapp-birthdays': {
      id: '/api/public/cron/whatsapp-birthdays'
      path: '/api/public/cron/whatsapp-birthdays'
      fullPath: '/api/public/cron/whatsapp-birthdays'
      preLoaderRoute: typeof ApiPublicCronWhatsappBirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/tithe-reminder': {
      id: '/api/public/cron/tithe-reminder'
      path: '/api/public/cron/tithe-reminder'
      fullPath: '/api/public/cron/tithe-reminder'
      preLoaderRoute: typeof ApiPublicCronTitheReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agenda/$siteId': {
      id: '/api/public/agenda/$siteId'
      path: '/api/public/agenda/$siteId'
      fullPath: '/api/public/agenda/$siteId'
      preLoaderRoute: typeof ApiPublicAgendaSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMarketplaceRouteChildren {
  AuthenticatedMarketplaceSlugRoute: typeof AuthenticatedMarketplaceSlugRoute
}

const AuthenticatedMarketplaceRouteChildren: AuthenticatedMarketplaceRouteChildren =
  {
    AuthenticatedMarketplaceSlugRoute: AuthenticatedMarketplaceSlugRoute,
  }

const AuthenticatedMarketplaceRouteWithChildren =
  AuthenticatedMarketplaceRoute._addFileChildren(
    AuthenticatedMarketplaceRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAcaoSocialRoute: typeof AuthenticatedAcaoSocialRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAusenciasRoute: typeof AuthenticatedAusenciasRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBoletimRoute: typeof AuthenticatedBoletimRoute
  AuthenticatedCampanhasRoute: typeof AuthenticatedCampanhasRoute
  AuthenticatedCelulasRoute: typeof AuthenticatedCelulasRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedCheckinInfantilRoute: typeof AuthenticatedCheckinInfantilRoute
  AuthenticatedCongregacoesRoute: typeof AuthenticatedCongregacoesRoute
  AuthenticatedContasBancariasRoute: typeof AuthenticatedContasBancariasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDecisoesRoute: typeof AuthenticatedDecisoesRoute
  AuthenticatedDevocionalRoute: typeof AuthenticatedDevocionalRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEbdRoute: typeof AuthenticatedEbdRoute
  AuthenticatedEmbedRoute: typeof AuthenticatedEmbedRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedEscalasRoute: typeof AuthenticatedEscalasRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedFamiliasRoute: typeof AuthenticatedFamiliasRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedJornadaEspiritualRoute: typeof AuthenticatedJornadaEspiritualRoute
  AuthenticatedLivroCaixaRoute: typeof AuthenticatedLivroCaixaRoute
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRouteWithChildren
  AuthenticatedMembrosRoute: typeof AuthenticatedMembrosRoute
  AuthenticatedMinisteriosRoute: typeof AuthenticatedMinisteriosRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOracoesRoute: typeof AuthenticatedOracoesRoute
  AuthenticatedPatrimonioRoute: typeof AuthenticatedPatrimonioRoute
  AuthenticatedPoliticaPrivacidadeRoute: typeof AuthenticatedPoliticaPrivacidadeRoute
  AuthenticatedPrivacidadeRoute: typeof AuthenticatedPrivacidadeRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
  AuthenticatedSecretariaRoute: typeof AuthenticatedSecretariaRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransmissoesRoute: typeof AuthenticatedTransmissoesRoute
  AuthenticatedTypesRoute: typeof AuthenticatedTypesRoute
  AuthenticatedVisitantesRoute: typeof AuthenticatedVisitantesRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedAdminDomainsRoute: typeof AuthenticatedAdminDomainsRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminTestDataRoute: typeof AuthenticatedAdminTestDataRoute
  AuthenticatedAdminWhatsappRoute: typeof AuthenticatedAdminWhatsappRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcaoSocialRoute: AuthenticatedAcaoSocialRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAusenciasRoute: AuthenticatedAusenciasRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBoletimRoute: AuthenticatedBoletimRoute,
  AuthenticatedCampanhasRoute: AuthenticatedCampanhasRoute,
  AuthenticatedCelulasRoute: AuthenticatedCelulasRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedCheckinInfantilRoute: AuthenticatedCheckinInfantilRoute,
  AuthenticatedCongregacoesRoute: AuthenticatedCongregacoesRoute,
  AuthenticatedContasBancariasRoute: AuthenticatedContasBancariasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDecisoesRoute: AuthenticatedDecisoesRoute,
  AuthenticatedDevocionalRoute: AuthenticatedDevocionalRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEbdRoute: AuthenticatedEbdRoute,
  AuthenticatedEmbedRoute: AuthenticatedEmbedRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedEscalasRoute: AuthenticatedEscalasRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedFamiliasRoute: AuthenticatedFamiliasRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedJornadaEspiritualRoute: AuthenticatedJornadaEspiritualRoute,
  AuthenticatedLivroCaixaRoute: AuthenticatedLivroCaixaRoute,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRouteWithChildren,
  AuthenticatedMembrosRoute: AuthenticatedMembrosRoute,
  AuthenticatedMinisteriosRoute: AuthenticatedMinisteriosRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOracoesRoute: AuthenticatedOracoesRoute,
  AuthenticatedPatrimonioRoute: AuthenticatedPatrimonioRoute,
  AuthenticatedPoliticaPrivacidadeRoute: AuthenticatedPoliticaPrivacidadeRoute,
  AuthenticatedPrivacidadeRoute: AuthenticatedPrivacidadeRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
  AuthenticatedSecretariaRoute: AuthenticatedSecretariaRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransmissoesRoute: AuthenticatedTransmissoesRoute,
  AuthenticatedTypesRoute: AuthenticatedTypesRoute,
  AuthenticatedVisitantesRoute: AuthenticatedVisitantesRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedAdminDomainsRoute: AuthenticatedAdminDomainsRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminTestDataRoute: AuthenticatedAdminTestDataRoute,
  AuthenticatedAdminWhatsappRoute: AuthenticatedAdminWhatsappRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NSlugRouteChildren {
  NSlugPostIdRoute: typeof NSlugPostIdRoute
}

const NSlugRouteChildren: NSlugRouteChildren = {
  NSlugPostIdRoute: NSlugPostIdRoute,
}

const NSlugRouteWithChildren = NSlugRoute._addFileChildren(NSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ASiteIdRoute: ASiteIdRoute,
  CMemberIdRoute: CMemberIdRoute,
  CertIdRoute: CertIdRoute,
  CheckinSessionIdRoute: CheckinSessionIdRoute,
  DSlugRoute: DSlugRoute,
  DecSiteIdRoute: DecSiteIdRoute,
  ESlugRoute: ESlugRoute,
  EnderecosSlugRoute: EnderecosSlugRoute,
  EventosSlugRoute: EventosSlugRoute,
  NSlugRoute: NSlugRouteWithChildren,
  OSiteIdRoute: OSiteIdRoute,
  PpSiteIdRoute: PpSiteIdRoute,
  ProtocoloIdRoute: ProtocoloIdRoute,
  ReciboDonationIdRoute: ReciboDonationIdRoute,
  VSiteIdRoute: VSiteIdRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicWhatsappOptOutRoute: ApiPublicWhatsappOptOutRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ManifestSiteIdJsonRoute: ManifestSiteIdJsonRoute,
  ApiPublicAgendaSiteIdRoute: ApiPublicAgendaSiteIdRoute,
  ApiPublicCronTitheReminderRoute: ApiPublicCronTitheReminderRoute,
  ApiPublicCronWhatsappBirthdaysRoute: ApiPublicCronWhatsappBirthdaysRoute,
  ApiPublicCronWhatsappDispatchRoute: ApiPublicCronWhatsappDispatchRoute,
  ApiPublicInstagramCallbackRoute: ApiPublicInstagramCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
